### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by bernardolm** [goreleaser/goreleaser.github.io#11]
_If you don’t want to create a tag yet, you can also create a release based on the latest commit by using the --snapshot flag. (Note: **ony** GitHub supports snapshots)_

**Comment by mavogel** [comment]
Thanks for catching this one. We will also add gitea to the release providers which support snapshots

**Comment by caarlos0** [comment]
thanks, fixed in https://github.com/goreleaser/goreleaser/commit/2c08ab87a13ce4a70cf89a691fbbc46c7da6c2e6
